### ISSUE TITLE
[BUG] Atlas entries do not show on fresh install

### ISSUE THREAD

**Issue by TimMonko** [brainglobe/brainrender-napari#148]
**Describe the bug**
On a fresh pip install of either brainrender-napari or brainglobe when I open brainrender there is no atlases in the atlas viewer. I have never used brainglobe before, so maybe this is the expected behavior? Documentation makes me think otherwise. 

**Expected behaviour**
There would be a list of atlases I can click on as according to [the tutorial.](https://brainglobe.info/tutorials/visualise-atlas-napari.html )

**Screenshots**
![image](https://github.com/brainglobe/brainrender/assets/47310455/cc3fae06-bb3d-4657-ae5b-85f9c66de8b6)

**Computer used (please complete the following information):**
napari: 0.4.19.post1
Platform: Windows-10-10.0.22631-SP0
Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]

**Comment by alessandrofelder** [comment]
Thanks again for reporting this @TimMonko - I'll update the documentation now, but if you upgrade your `brainrender-napari` by running `pip install -U brainrender-napari` in your activate conda-environment, you will get an additional widget to download/update atlases via BrainGlobe - let us know how you get on!
