### ISSUE TITLE
[BUG] Tests fail in CI - investigation needed

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainrender-napari#158]
**Describe the bug**

**To Reproduce**
Please enter full details of how to reproduce this bug.

**Expected behaviour**

**Log file**
Please attach the log file if relevant (e.g. `output/cellfinder_2019-12-17_13-29-46.log`)

**Screenshots**

**Computer used (please complete the following information):**

- OS: [e.g. Linux, Windows, macOS] For macOS, please specify if you have an Intel or M1 CPU (M1 is likely if your mac is new).
- Version [e.g. 18.04]
- Hardware specs [e.g. 128 GB RAM, Xeon 4114 CPU].

**Additional context**

**Comment by adamltyson** [comment]
Test failures seem to be due to slow download of atlases (related to https://github.com/brainglobe/brainglobe-atlasapi/issues/407).
