### ISSUE TITLE
Allow user to hover over a brain region and see the metadata.

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainrender-napari#26]
This is currently implemented within brainreg-segment:

https://github.com/brainglobe/brainreg-segment/blob/a84d4b2fab53c256590b79d57beb1eac5810ef0f/brainreg_segment/segment.py#L91-L105

Ideally this would:
1. use tooltips instead (https://github.com/brainglobe/brainreg-segment/issues/89)
2. Be visible regardless of what layers are added/visible (as long as one is!), not just the annotations layer

I think for 1. the metadata would have to be added to the annotation layer itself

**Comment by adamltyson** [comment]
@alessandrofelder this is a feature that I've been asked for a lot. If it's not too much work, it would be great to have in the initial release.

**Comment by alessandrofelder** [comment]
OK - added it to the first milestone
