### ISSUE TITLE
User instructions about basic brainrender-napari UI functionality

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainrender-napari#52]
We should have an intuitive way for users to find out they can double-click on the atlas table view and structure tree view to add things to napari. Maybe an info logo to hover over? More/alternative suggestions welcome!

https://github.com/brainglobe/brainglobe-napari/pull/49#issuecomment-1653720850

**Comment by adamltyson** [comment]
This is probably a good thing to get some user feedback on. Maybe we should just wander around SWC with a laptop?

**Comment by alessandrofelder** [comment]
* double-clicking
* hovering
* right-clicking
Should all be part of a user guide and discussed with users for feedback
