### ISSUE TITLE
brainrender widget should have brainglobe logo at top

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainrender-napari#78]

**Comment by adamltyson** [comment]
Shall we create the `bg-napari-utils` package, and begin it with some standard html that can be added to the top of every widget?

**Comment by alessandrofelder** [comment]
Ultimately, yes!
I'm tempted to do a copy-paste job for this milestone, so we can get a release and user feedback earlier (I don't want to ask users to `pip install` from github?
